plugins {
    id 'com.android.application'
}

android {
    namespace = "com.xlk.example"
    compileSdk = 31

    defaultConfig {
        applicationId = "com.xlk.example"
        minSdk = 21
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    //解决API 28只创建arm64目录，导致找不到库的问题
    splits {
        abi {
            enable true // 启用ABI拆分
            reset() // 重置ABI列表
            include 'armeabi-v7a', 'arm64-v8a' // 指定要拆分的架构
            universalApk false // 是否生成通用APK（包含所有架构）
        }
    }

    packagingOptions {
        resources.pickFirsts.add("lib/armeabi-v7a/libc++_shared.so")
        resources.pickFirsts.add("lib/arm64-v8a/libc++_shared.so")
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'androidx.activity:activity:1.5.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation("org.greenrobot:eventbus:3.3.1")
//    implementation 'com.gitee.xlk_gitee:mupdf-library:6.0.14'
    implementation(project(":mupdf"))

    implementation 'com.blankj:utilcodex:1.31.1'
}