plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace = "com.xlk.mupdf.library"
    compileSdk = 32

    defaultConfig {
        minSdk = 21

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles("consumer-rules.pro")
//        ndk {
//            // 设置支持的SO库
//            abiFilters 'armeabi-v7a','arm64-v8a'
//        }
    }

//    sourceSets {
//        main {
//            // mac 电脑上：nativeLibs  windows电脑上：jniLibs
//            jniLibs.srcDirs = ['src/main/jniLibs']     //设置目标的so存放路径
//            jni.srcDirs = [] //禁用自动调用ndk-build
//        }
//    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.5.0'
    implementation 'org.greenrobot:eventbus:3.3.1'
}

//https://github.com/jitpack/android-example
publishing {
    publications {
        release(MavenPublication) {
            groupId = 'com.gitee.xlk_gitee'
            artifactId = 'mupdf-library'
            version = '6.0.11'

            afterEvaluate {
                from components.release
            }
        }
    }
}