plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace = "com.xlk.mupdf.library"
    compileSdk = 32

    defaultConfig {
        minSdk = 21

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles("consumer-rules.pro")
        ndk {
            // 设置支持的SO库
            abiFilters.add("armeabi-v7a")
        }
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}
afterEvaluate {
    publishing {
        publications {
            // Creates a Maven publication called "release".
            group = 'com.gitee.xlk_gitee'
            version = '1.0.2'
            //发布release版本
            release(MavenPublication) {
                // Applies the component for the release build variant.
                from components.release
                //groupId通常是自己的gitee或者GitHub的账户地址
                groupId = group
                //artifactId通常是指待发布项目的名称，也就是别名
                artifactId = 'mupdf-library'
                //version通常是指待发布项目的版本号，这里是写死的，通常我们取项目versionName
                version = version
            }
        }
    }
}

dependencies {

    implementation(libs.appcompat)
    implementation(libs.material)
    implementation(libs.eventbus)
}